events {}

http {

   resolver 127.0.0.11 valid=10s ipv6=off;

    upstream portal_backend {
        zone portal_backend 64k;
        server portal:8080 resolve;
    }

    upstream core_api_backend {
        zone core_api_backend 64k;
        server core-api:8081 resolve;
    }

    upstream status_backend {
        zone status_backend 64k;
        server status:8082 resolve;
    }

    server {
        listen 80;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-Frame-Options "DENY" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        
        location = /api/core-health {
            proxy_pass http://core_api_backend/health;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

        location = /api/status {
            proxy_pass http://status_backend/api/status;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
            proxy_pass http://core_api_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            proxy_pass http://portal_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}